#version: '3.10'

services:
  web:
    build: .
    expose:
      - "5000"
    depends_on:
      - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379


  redis:
    image: "redis:alpine"
    ports:
      - "6379"
    volumes:
      - redis_data:/data


  nginx:
   image: nginx:latest
   ports:
    - "5000:5000"
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
   depends_on:
    - web 
volumes:
  redis_data: